### PR TITLE
Fix/26

### PR DESCRIPTION
**Pull request by Vannsl**
Fixes [#26](https://github.com/Vannsl/vue-contenteditable-form/issues/26) and fixes [#22](https://github.com/Vannsl/vue-contenteditable-form/issues/22)

### CODE REVIEW

**Comment by ReneCode** [comment]
thanks for fixing the image-block selection behaviour.

when I created that image-ability I do a quick implementation. But over time I`m not sure wether it`s a good idea to create a complete new component.

**Comment by ReneCode** [comment]
now you are able to create a lot of empty blocks on ``cursor-down`` on the last block. :-(

**Review by ReneCode — COMMENTED** [review]
please add:
```
    isLastBlock: {
      type: Boolean,
      default: true,
    }
``` 
to EditableBlock  properties

**Review by ReneCode — CHANGES_REQUESTED** [review]
with that ``isLastBlock`` property it will work as expected.

**Comment by Vannsl** [comment]
Oh, boy I wanted to copy/paste the block also to the image block (until I realized I don't need it there) and accidentalls used Cmd+X instead of Cmd+C. Thanks for noticing

**Review by ReneCode — APPROVED** [review]

**Comment by ReneCode** [comment]
now it looks fine - ready to go to production.

**Pull request merged**
